version = 0.1

[default.deploy.parameters]
stack_name = "kaiassistant-api-stack"
s3_prefix = "kaiassistant-api"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
image_repositories = []
